
gcp_service_account_json = """
{ 
  "type": "service_account",
  "project_id": "eikenp2-quiz-sheets",
  "private_key_id": "1fd661623da066b1b6c35eee52f931269b5240e1",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsdlcRVL/8UX8V\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-sheets-access@eikenp2-quiz-sheets.iam.gserviceaccount.com",
  "client_id": "112307688513037609916",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access@eikenp2-quiz-sheets.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
