[gcp_service_account]
type = "service_account"
project_id = "eikenp2-quiz-sheets"
private_key_id = "1fd661623da066b1b6c35eee52f931269b5240e1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsdlcRVL/8UX8V
GHirMN3MFenSUx4Qezjl033iZZUeAg4wo1vXgg22LktOwONCKs/WgZexQc4e+32L
rwNUZJXQanMbOgLxIGdTRzqzCBZe5Jmg1NcqLYXFQ6CJ4/1hYWwjnWnsoenKZ4G3
aem+2ALXFo6CIE0q4MurJeKzrjHFN0zWNh2j4RW2QoYJW5+YaRFZJfYZzmOHMdDz
jxNi/wWruK3HbuvsbKqDYKffHAqkb72mB14NgMBLa4RyokhrD71gMd92cx2WMNqn
TrjRUlhtEz8t3Nc8gcpArJ74II8tCFRjdpcPBzcjrisWASFZbyGze4ms1UUMSCC0
74ykVUfRAgMBAAECggEAAXIFuTUlQo947TDBoU2ritctcGUxhF02ivg/OClD5TNv
oVNAigKwL1zMznYO+EZdQ8ZW58HUzNWspcvk3LlCqrNy9MgXeZa372SjVAqwd9Wo
HTmXOfPmdJYMuOv44BdtxrIBklA+IjYIFEhkpOk+V8wxptRHUUnxccbQ+5YBhuJw
qdQexxH3v5s/Wj4cadGjP3DZNVbur8iu8ITwN9xnZX68Ab6N2yGJwYlH2FkQOhtP
1NPdiFhyvjB+H4dWOYXivSsAEEoMK2jiqUx/fViMTHwN9YsUZcUzBjwzP+l2r/kL
4QY23nwAz2ZRY6kNhWwao57HB2hDFxfU5TVmxbbO8QKBgQDWoQLGiA7KhgYp4sZa
7ydlNRL6GnZ3CdMlqWaUOZND/HNKlBBr8wLwID4FAReEBvpVIap34GOfh9RGwhkX
J3BdLPUAd/cHnoozFHZ+NP0gCeyxXAOioZaCQ8eiRgUjcalSIM2b9i96N/DxqF9k
WrfYRFAIXtMa59rTa5gUYu5gmwKBgQDNtJcLPsxFJ/iNZncVmGejl53qsHxps+zB
flFdO0iVIqaD2S3STFBkRnEtPrwjaH3TmeUSVLcD9mG3jAp8H3ZWPYPT8W6HAu8V
oSt2GKLBRtMwWY61obrt4ZXlSlqs5vaT/M2IKj7M5g/eIs3VQUUkeQI8lRW0Tdin
EuST8hHSAwKBgBEfDwWfXO6y+lLlEEW4xj/AmB7zdXfRhNKATPqODT1jKh9M6HJ0
FEvrhocHq0SQ+e9InDyr3cagI0LxwOaj8sa8C19aMo6dCxFAFKPEvlyL7iHH4VJb
6ZHCrm43f7lwG729eCl03hy10ba1Y8axpfDOokPIrLZ8wGwVLTCTI8j5AoGAGuvU
jLs2PqLBi7fqQ+BDSAyytSFN1wOeK6Cdg2cb07DKPB0zOv+T0dvKOhKoyrWFKilM
6n49yX34Qe5I/P+dHCJG23kQbwj6Q0lph7YnrsXXI8/Eto6pCTLpzC1T+qbrhGik
eXqV53kAgKDrcUpugxx3J3iXc5ZwkUUOtzIKFQMCgYBKa4iEX4xNAuqTwgH7v+/U
91iroSZhtW0puZw0X6uqWg+E36ulLNgf9Gj00dnHH/XoJLnV5tjLTHce/YV7DEg2
h9xeArtqpj7UguZOjpJ6O9+zdWhetVf7LhokSeWEwEPW/g7RxFAGk2fde9LPKTri
FQSwWIBV/qLAU134WFZSJg==
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-access@eikenp2-quiz-sheets.iam.gserviceaccount.com"
client_id = "112307688513037609916"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access@eikenp2-quiz-sheets.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
